In [1]:
import os
os.listdir('../data')

['PovStatsFootNote.csv',
 'PovStatsCountry-Series.csv',
 'PovStatsCountry.csv',
 'lat_long.csv',
 'PovStatsData.csv',
 'poverty.csv',
 'PovStatsSeries.csv']

In [3]:
import pandas as pd
poverty_data = pd.read_csv('../data/PovStatsData.csv')
poverty_data.head(3)

,Country Name,Country Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 50
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PC40.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT10.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT60.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN